<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-DXGFWYGN7R"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-DXGFWYGN7R');
    </script>

    <!-- Meta tags -->
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="width">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
    <!-- Page title -->
    <title>RedM Server Hosting - FreakHosting</title>
    <meta name="description" content="Premium RedM (RDR2) Dedicated Server Hosting, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable RedM game server now!">
    <meta name="keywords" content="redm,red m,red dead redemption 2,redm 2,hosting,host,server,servers,ddos,protection,ddos protection,path.net,linux,windows,gaming,game,romania,bacau,germany,frankfurt,usa,dallas,texas,vps,dedicated server,premium,best,affordable,cheap,how to,freakhosting">
    <meta name="robots" content="index,follow">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="blue">
    <meta name="apple-mobile-web-app-title" content="FREAKHOSTING GameServer" />
    <link rel="apple-touch-icon" href="/assets/images/touch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/images/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="167x167" href="/assets/images/touch-icon-ipad-retina.png">


    <meta name="format-detection" content="telephone=yes">
    <meta name="theme-color" content="#2ed2fa">

	<link rel="alternate" hreflang="x-default" href="https://freakhosting.com/redm-server-hosting" />
     
    <link rel="alternate" hreflang="en-GB" href="https://freakhosting.com/redm-server-hosting" />
    <link rel="canonical" href="https://freakhosting.com/redm-server-hosting" />

	<meta property="og:locale" content="en_US">
    <meta property="og:type" content="website">
    <meta property="og:title" content="RedM Server Hosting - FreakHosting">
    <meta property="og:description" content="Premium RedM (RDR2) Dedicated Server Hosting, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable RedM game server now!">
    <meta property="og:url" content="https://freakhosting.com/redm-server-hosting">
    <meta property="og:site_name" content="freakhosting.com">
    <meta property="og:image" content="https://freakhosting.com/assets/marketing/banneren.png">
  
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@freakhosting">
    <meta name="twitter:creator" content="@freakhosting">
    <meta name="twitter:description" content="Premium RedM (RDR2) Dedicated Server Hosting, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable RedM game server now!">
    <meta name="twitter:title" content="RedM Server Hosting - FreakHosting">
    <meta name="twitter:image" content="https://freakhosting.com/assets/marketing/banneren.png">


    <!-- FontAwesome 5 Pro -->
    <link href="https://cdn.jsdelivr.net/gh/hung1001/font-awesome-pro@0ac23ca/css/all.css" rel="stylesheet" type="text/css">

    <!-- Raleway Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

	<!-- Bootstrap 5.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="assets/css/custom.css">

 

 
 

<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Product",
    "@id": "https://freakhosting.com/redm-server-hosting",
    "url": "https://freakhosting.com/redm-server-hosting",
    "name": "RedM Server Hosting - FreakHosting",
    "image": "https://freakhosting.com/assets/marketing/banneren.png",
    "description": "Premium RedM (RDR2) Dedicated Server Hosting, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable RedM game server now!",
    "brand": {
      "@type": "Organization",
      "name": "FREAKHOSTING",
      "url": "https://freakhosting.com",
      "logo": "/assets/images/logo.webp"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "4.9",
      "ratingCount": "107",
      "bestRating": "5",
      "worstRating": "1"
    },
    "review": [{
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Alexandru"
      },
      "reviewBody": "Bought a GTA5 server hosting and I am more than happy with the service provided. Setup the server with TxAdmin in couple minutes and had no issues. Hope it will stay like this"
    }, {
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Spritz"
      },
      "reviewBody": "Absolutely amazing, there may be some features that arent included, but for the price it is way more than excellent. The support team in their discord responds quick and always seems to help out, aswell as solve problems. I will continue to use this hosting service for my FiveM server as it stays the best for pricing and my needs. Thank you FreakHosting for providing such an amazing experience and service."
    }, {
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Alex"
      },
      "reviewBody": "Best service, never let me down, best quality and extremely fast customer service!"
    }],
    "offers": {
      "@type": "AggregateOffer",
      "lowPrice": 3.99,
      "highPrice": 15.99,
      "priceCurrency": "EUR",
      "offerCount": 4,
      "offers": [{
        "@type": "Offer",
        "price": 3.99,
        "name": "RedM Small",
        "description": "REDM GAME HOSTING",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best RedM Server hosting on the market"
        },
        "url": "https://freakhosting.com/clientarea/store/game-hosting/host-redm",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 7.99,
        "name": "RedM Standard",
        "description": "REDM GAME HOSTING",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best RedM Server hosting on the market"
        },
        "url": "https://freakhosting.com/clientarea/store/game-hosting/host-redm",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 11.99,
        "name": "RedM Large",
        "description": "REDM GAME HOSTING",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best RedM Server hosting on the market"
        },
        "url": "https://freakhosting.com/clientarea/store/game-hosting/host-redm",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 15.99,
        "name": "RedM Supreme",
        "description": "REDM GAME HOSTING",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best RedM Server hosting on the market"
        },
        "url": "https://freakhosting.com/clientarea/store/game-hosting/host-redm"
      }]
    }
  }
</script>

</head>
<body>

	<?php require 'includes/header.php'; ?>
    <div class="header-inner" style="background-image: url('assets/images/services-header/redm-header.webp');background-size: cover;height: 400px;">
        <div class="container-fluid container-freak h-100">
            <div class="row d-flex justify-content-between align-items-center h-100">
                <div class="col-lg-8">
                    <h1>RedM Server Hosting  </h1>
                    <p>Elevate your gaming experience with FREAKHOSTING, your premium choice for hosting RedM servers. With strategic locations in Germany, Romania or the USA, our dedicated hosting service ensures optimal gameplay. Benefit from advanced DDoS protection provided by Path.net, capable of supporting an impressive 17Tbps. We offer enterprise infrastructure, powered by the latest generation AMD Ryzen 9 processors, for swift, secure, and low-latency connections. Trust FREAKHOSTING to host your gaming world, and step into the future of immersive gaming.</p>
                </div>
            </div>
        </div>
    </div>

<!-- Game Packages -->
<div class="game-packages pt-5 pb-1">
		<div class="container-fluid container-freak">
			<h2 class="site-title text-uppercase mb-5">Latest Offers</h2>
			<div class="row">
				<div class="col-md-3">
	                <div class="card mb-4">
	                	<div class="card-body">
                            <p class="package-name mb-1" style="font-size: 15px;">Small</p>
	                		<h5 class="card-title mb-3" style="font-size: 30px;">2GB RAM</h5>
	                		<ul class="text-left">
                                <li><i class="fas fa-microchip"></i> AMD Ryzen 9 5900x</li>
                                <li><i class="fas fa-user"></i> Unlimited Players</li>
								<li><i class="fas fa-ethernet"></i> Port 30120</li>
                                <li><i class="fas fa-database"></i> MySQL Database</li>
                                <li><i class="fas fa-shield"></i> Premium DDoS Protection</li>
                      </ul>
                      <h5 class="card-title mb-4"><span>&euro; 3.99</span><span class="slot">/mo</span></h5>
                      <a data-bs-toggle="modal" data-bs-target="#plan-one" class="btn w-100">
                        <i class="fas fa-globe"></i> Choose Location
                      </a>
	                	</div>
	                </div>
            	</div>
            	<div class="col-md-3">
	                <div class="card mb-4">
	                	<div class="card-body">
                            <p class="package-name mb-1" style="font-size: 15px;">Standard</p>
	                		<h5 class="card-title mb-3" style="font-size: 30px;">4GB RAM</h5>
	                		<ul class="text-left">
                                <li><i class="fas fa-microchip"></i> AMD Ryzen 9 5900x</li>
                                <li><i class="fas fa-user"></i> Unlimited Players</li>
								<li><i class="fas fa-ethernet"></i> Port 30120</li>
                                <li><i class="fas fa-database"></i> MySQL Database</li>
                                <li><i class="fas fa-shield"></i> Premium DDoS Protection</li>
                      </ul>
                      <h5 class="card-title mb-4"><span>&euro; 7.99</span><span class="slot">/mo</span></h5>
                      <a data-bs-toggle="modal" data-bs-target="#plan-one" class="btn w-100">
                        <i class="fas fa-globe"></i> Choose Location
                      </a>
	                	</div>
	                </div>
            	</div>
            	<div class="col-md-3">
	                <div class="card mb-4">
	                	<div class="card-body">
	                		<p class="package-name mb-1" style="font-size: 15px;">Large</p>
	                		<h5 class="card-title mb-3" style="font-size: 30px;">6GB RAM</h5>
	                		<ul class="text-left">
                                <li><i class="fas fa-microchip"></i> AMD Ryzen 9 5900x</li>
                                <li><i class="fas fa-user"></i> Unlimited Players</li>
								<li><i class="fas fa-ethernet"></i> Port 30120</li>
                                <li><i class="fas fa-database"></i> MySQL Database</li>
                                <li><i class="fas fa-shield"></i> Premium DDoS Protection</li>
                      </ul>
                      <h5 class="card-title mb-4"><span>&euro; 11.99</span><span class="slot">/mo</span></h5>
                      <a data-bs-toggle="modal" data-bs-target="#plan-one" class="btn w-100">
                        <i class="fas fa-globe"></i> Choose Location
                      </a>
	                	</div>
	                </div>
            	</div>
            	<div class="col-md-3">
	                <div class="card mb-4">
	                	<div class="card-body">
                            <p class="package-name mb-1" style="font-size: 15px;">Supreme</p>
	                		<h5 class="card-title mb-3" style="font-size: 30px;">8GB+ RAM</h5>
	                		<ul class="text-left">
                                <li><i class="fas fa-microchip"></i> AMD Ryzen 9 5900x</li>
                                <li><i class="fas fa-user"></i> Unlimited Players</li>
								<li><i class="fas fa-ethernet"></i> Port 30120</li>
                                <li><i class="fas fa-database"></i> MySQL Database</li>
                                <li><i class="fas fa-shield"></i> Premium DDoS Protection</li>
                      </ul>
                      <h5 class="card-title mb-4"><span>&euro; 15.99</span><span class="slot">/mo</span></h5>
                      <a data-bs-toggle="modal" data-bs-target="#plan-one" class="btn w-100">
                        <i class="fas fa-globe"></i> Choose Location
                      </a>
	                	</div>
	                </div>
            	</div>
			</div>
		</div>
	</div>

	<div class="server-features pt-5 pb-1">
		<div class="container-fluid container-freak">
			<h2 class="site-title text-uppercase mb-5">What we offer ?</h2>
			<div class="row">
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/24-hours.svg" alt="Support 24/7">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Support <span class="d-block">24/7</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">We are always here for you. Our 24/7 Support Team is here to solve any commercial or technical problem that you might have.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/shield.svg" alt="DDoS Protection">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">DDoS <span class="d-block">Protection</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">All services are on enterprise level of protection against DDoS attacks up to 17Tbps to keep your services online with ease.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/uptime.svg" alt="99.99% Uptime">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Uptime <span class="d-block">99.5%</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">Thanks to our infrastructure located in the best datacenters with the most reliable uplinks, we offer our clients an uptime of 99.5% for their services.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/cpu.svg" alt="Processor">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Ultra-Fast <span class="d-block">Infrastructure</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">Our hosting network is built on high-performance AMD Ryzen 9 dedicated servers resulting in unmatched game server performance.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/panel.svg" alt="Control Panel">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Game <span class="d-block">Panel</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">Pterodactyl is the premium control panel we use for game servers, a user-friendly and efficient panel perfect for you to manage any project.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/active.svg" alt="Instant Setup">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Instant <span class="d-block">Setup</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">After the placement of an order, the installation process of our services begins immediately after payment confirmation.</p>
							<br>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>



    <div class="preview-panel py-5">
        <div class="container">
            <h2 class="site-title text-uppercase text-center">Powered by Pterodactyl</h2>
            <p class="text-center mb-5">Pterodactyl is the premium panel used by us to control gaming services, offering our clients a user-friendly and efficient platform for project management.</p>
            <ul class="nav nav-justified" data-bs-tabs="" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-bs-toggle="tab" href="#serverconsole" role="tab">
                        <img class="img-fluid mb-1" src="assets/images/console.svg" alt="GamePanel Server Console" title="Server Console">
                        <h4>Server Console</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="tab" href="#filemanager" role="tab">
                        <img class="img-fluid mb-1" src="assets/images/plus.svg" alt="GamePanel File Manager" title="File Manager">
                        <h4>File Manager</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="tab" href="#pluginmanager" role="tab">
                        <img class="img-fluid mb-1" src="assets/images/gpanel.svg" alt="GamePanel Plugin Manager" title="Plugin Manager">
                        <h4>Plugin Manager</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="tab" href="#auditlogs" role="tab">
                        <img class="img-fluid mb-1" src="assets/images/dll.svg" alt="GamePanel Audit Logs" title="Audit Logs">
                        <h4>Audit Logs</h4>
                    </a>
                </li>
            </ul>
            <div class="tab-content mt-5">
                <div class="tab-pane active text-center" id="serverconsole" role="tabpanel">
                    <img class="img-fluid rounded" src="assets/images/g-console.webp" alt="Panel Server Console">
                </div>
                <div class="tab-pane text-center" id="filemanager" role="tabpanel">
                    <img class="img-fluid rounded" src="assets/images/g-filemanager.webp" alt="Panel File Manager">
                </div>
                <div class="tab-pane text-center" id="pluginmanager" role="tabpanel">
                    <img class="img-fluid rounded" src="assets/images/g-pluginmanager.webp" alt="Panel Plugin Manager">
                </div>
                <div class="tab-pane text-center" id="auditlogs" role="tabpanel">
                    <img class="img-fluid rounded" src="assets/images/g-auditlogs.webp" alt="Panel Audit Logs">
                </div>
            </div>
        </div>
    </div>

    <div class="dark py-5">
        <div class="container-fluid container-freak">
            <h2 class="site-title text-uppercase mb-5">Why RedM Server Hosting</h2>
            <p>RedM is a trailblazing modification platform tailored for the world of Red Dead Redemption 2. This mod breathes fresh life into the already expansive Western landscapes of RDR2, unlocking its multiplayer potential beyond the original Red Dead Online. With RedM, players and enthusiasts can craft and dive into custom game modes, unique role-playing experiences, and scripted adventures, all set against the rich backdrop of the late American frontier. By granting such creative freedom, RedM has become the nexus for a new era of cowboy-centric stories, multiplayer showdowns, and immersive narratives.<br><br>
            When considering hosting for your RedM server, there's only one name to trust: FREAKHOSTING. Our hosting solutions are precisely calibrated for the complex demands of RedM, ensuring every gunfight, horseback chase, and campfire tale is experienced in its full glory, free from lags or disruptions. Immerse your players in the Wild West with the confidence that our state-of-the-art infrastructure and steadfast support will keep your server at peak performance. With FREAKHOSTING, your RedM adventures are bound to be legendary. Saddle up and ride into the future of Red Dead multiplayer with FREAKHOSTING as your trusted companion.</p>
        </div>
    </div>

    <div class="faq py-5">
        <div class="container-fluid container-freak">
            <h2 class="site-title text-uppercase mb-5">Frequently Asked Questions</h2>
            <div class="accordion" id="accordionExample">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
									How do I pay?
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
									<p>Available payment methods by which you can purchase a service are: Paypal, Credit Card, Paysafecard, Cryptocurrencies, Bank Transfer</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingTwo">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
									How long does it take to activate a purchased service?
                                </button>
                            </h2>
                            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>After the placement of an order, the installation process of our server begins immediately after payment confirmation.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingThree">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
									What do I do if I did not receive the data of the purchased service by email?
                                </button>
                            </h2>
                            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
									<p>In case you did not receive the data by email, please also check the SPAM section, sometimes it may be there. If the email is nowhere to be found, please open a ticket at the Billing department.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingFour">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                                	What infrastructure is FREAKHOSTING using for game servers?
                                </button>
                            </h2>
                            <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>All game servers purchased from us are hosted on high-performance AMD Ryzen 9 servers with ultra-fast NVMe SSD storage and DDR4 RAM.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingFive">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
                                Where are the game servers hosted? What latency will I get on the server?
                                </button>
                            </h2>
                            <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>Our hosting network is located in Romania, Germany and USA in the best datacenters with the most reliable uplinks. Depending on which location you will choose we will try to provide the lowest latency possible.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php require 'includes/footer.php'; ?>


    <!-- Modals for Plans -->
    <!-- Modal -->
    <div class="modal fade" id="plan-one" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="far fa-times"></i></button>
                    <h2 class="text-center mt-5">Pick the location of your server</h2>
                    <p class="text-center mb-2">Choose the location closest to your players, for the best connection speeds!</p>
                    <p class="text-center mb-2">You can check the latency on <a href="https://lg.freakhosting.com">lg.freakhosting.com</a></p>
                    <div class="row">
                        <div class="col-lg-4 mx-auto">
                            <a href="https://freakhosting.com/clientarea/store/game-hosting/host-redm" class="mo">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-center country">
                                            <div class="d-flex align-items-center">
                                                <img src="assets/images/romania.svg" alt="Romania Location FREAKHOSTING">
                                            </div>
                                            <div class="d-flex align-items-center ms-3">
                                                <div>
                                                    <h4 class="mb-0">Romania</h4>
                                                    <p class="mb-0">Bacau</p>
                                                    <p class="mb-0">(Voxility)</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-4 mx-auto">
                            <a href="https://freakhosting.com/clientarea/store/game-hosting/host-redm" class="mo">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-center country">
                                            <div class="d-flex align-items-center">
                                                 <img src="assets/images/germany.svg" alt="Germany Location FREAKHOSTING">
                                            </div>
                                            <div class="d-flex align-items-center ms-3">
                                                <div>
                                                    <h4 class="mb-0">Germany</h4>
                                                    <p class="mb-0">Frankfurt</p>
                                                    <p class="mb-0">(Path.net)</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-4 mx-auto">
                            <a href="https://freakhosting.com/clientarea/store/game-hosting/host-redm" class="mo">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-center country">
                                            <div class="d-flex align-items-center">
                                                <img src="assets/images/usa.svg" alt="USA Location FREAKHOSTING">
                                            </div>
                                            <div class="d-flex align-items-center ms-3">
                                                <div>
                                                    <h4 class="mb-0">USA</h4>
                                                    <p class="mb-0">Dallas</p>
                                                    <p class="mb-0">(Path.net)</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 


<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="589395cd-679f-45bb-a565-c01d847f512b";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

<script src="https://cdn.websitepolicies.io/lib/cconsent/cconsent.min.js" defer></script><script>window.addEventListener("load",function(){window.wpcb.init({"border":"thin","corners":"small","colors":{"popup":{"background":"#222222","text":"#ffffff","border":"#2ED2FA"},"button":{"background":"#2ED2FA","text":"#000000"}},"padding":"small","margin":"small","fontsize":"small","content":{"href":"https://freakhosting.com/legal"}})});</script>

</body>
</html>