<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-DXGFWYGN7R"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-DXGFWYGN7R');
    </script>

    <!-- Meta tags -->
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="width">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
    <!-- Page title -->
    <title>Cheap Domain Names - FreakHosting</title>
    <meta name="description" content="Register your domain easily with our reliable domain registration services .com .net .ro .xyz .eu. Find and secure your perfect domain name for your website.">
    <meta name="keywords" content=".com,.net,.ro,.xyz,.eu,domains,buy domain,domain name,website domain,domain hosting,domain name registration,website name,get domain,domain registration,domain purchase,com domain,buy domain name,web domain hosting,web domain,buy website domain,internet domain,get domain name,available domains,domain and hosting,web names,available domain names,register url,domain name purchase,get a website domain,site domainfreakhosting">
    <meta name="robots" content="index,follow">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="blue">
    <meta name="apple-mobile-web-app-title" content="FREAKHOSTING GameServer" />
    <link rel="apple-touch-icon" href="/assets/images/touch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/images/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="167x167" href="/assets/images/touch-icon-ipad-retina.png">


    <meta name="format-detection" content="telephone=yes">
    <meta name="theme-color" content="#2ed2fa">

	<link rel="alternate" hreflang="x-default" href="https://freakhosting.com/register-domain" />
     
    <link rel="alternate" hreflang="en-GB" href="https://freakhosting.com/register-domain" />
    <link rel="canonical" href="https://freakhosting.com/register-domain" />

	<meta property="og:locale" content="en_US">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Cheap Domain Names - FreakHosting">
    <meta property="og:description" content="Register your domain easily with our reliable domain registration services .com .net .ro .xyz .eu. Find and secure your perfect domain name for your website.">
    <meta property="og:url" content="https://freakhosting.com/register-domain">
    <meta property="og:site_name" content="freakhosting.com">
    <meta property="og:image" content="https://freakhosting.com/assets/marketing/banneren.png">
  
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@freakhosting">
    <meta name="twitter:creator" content="@freakhosting">
    <meta name="twitter:description" content="Register your domain easily with our reliable domain registration services .com .net .ro .xyz .eu. Find and secure your perfect domain name for your website.">
    <meta name="twitter:title" content="Cheap Domain Names - FreakHosting">
    <meta name="twitter:image" content="https://freakhosting.com/assets/marketing/banneren.png">

    <!-- FontAwesome 5 Pro -->
    <link href="https://cdn.jsdelivr.net/gh/hung1001/font-awesome-pro@0ac23ca/css/all.css" rel="stylesheet" type="text/css">

    <!-- Raleway Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Bootstrap 5.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="assets/css/custom.css">

 

 


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Product",
    "@id": "https://freakhosting.com/register-domain",
    "url": "https://freakhosting.com/register-domain",
    "name": "Cheap Domain Names - FreakHosting",
    "image": "https://freakhosting.com/assets/marketing/banneren.png",
    "description": "Register your domain easily with our reliable domain registration services .com .net .ro .xyz .eu. Find and secure your perfect domain name for your website.",
    "brand": {
      "@type": "Organization",
      "name": "FREAKHOSTING",
      "url": "https://freakhosting.com",
      "logo": "/assets/images/logo.webp"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "4.9",
      "ratingCount": "107",
      "bestRating": "5",
      "worstRating": "1"
    },
    "review": [{
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Alexandru"
      },
      "reviewBody": "Bought a GTA5 server hosting and I am more than happy with the service provided. Setup the server with TxAdmin in couple minutes and had no issues. Hope it will stay like this"
    }, {
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Spritz"
      },
      "reviewBody": "Absolutely amazing, there may be some features that arent included, but for the price it is way more than excellent. The support team in their discord responds quick and always seems to help out, aswell as solve problems. I will continue to use this hosting service for my FiveM server as it stays the best for pricing and my needs. Thank you FreakHosting for providing such an amazing experience and service."
    }, {
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Alex"
      },
      "reviewBody": "Best service, never let me down, best quality and extremely fast customer service!"
    }],
    "offers": {
      "@type": "AggregateOffer",
      "lowPrice": 1.99,
      "highPrice": 99.99,
      "priceCurrency": "EUR",
      "offerCount": 4,
      "offers": [{
        "@type": "Offer",
        "price": 1.99,
        "name": ".eu Domain Registration",
        "description": "CHEAP DOMAIN NAMES REGISTRATION",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best domain names hosting on the market"
        },
        "url": "https://freakhosting.com/clientarea/cart.php?a=add&domain=register",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 10.99,
        "name": ".com Domain Registration",
        "description": "CHEAP DOMAIN NAMES REGISTRATION",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best domain names hosting on the market"
        },
        "url": "https://freakhosting.com/clientarea/cart.php?a=add&domain=register",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 8.99,
        "name": ".ro Domain Registration",
        "description": "CHEAP DOMAIN NAMES REGISTRATION",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best domain names hosting on the market"
        },
        "url": "https://freakhosting.com/clientarea/cart.php?a=add&domain=register",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 8.99,
        "name": ".uk Domain Registration",
        "description": "CHEAP DOMAIN NAMES REGISTRATION",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best domain names hosting on the market"
        },
        "url": "https://freakhosting.com/clientarea/cart.php?a=add&domain=register"
      }]
    }
  }
</script>

</head>
<body>

    <?php require 'includes/header.php'; ?>
    <div class="header-inner" style="background-image: url('assets/images/services-header/domain-header.webp');background-size: cover;height: 400px;">
        <div class="container-fluid container-freak h-100">
            <div class="row d-flex justify-content-between align-items-center h-100">
                <div class="col-lg-8">
                    <h1>Domain Registration</h1>
                    <p>Register your domain easily with our reliable domain registration services .com .net .ro .xyz .eu. Find and secure your perfect domain name for your website.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="domain-search py-5">
        <div class="container-fluid container-freak">
            <div class="row d-flex justify-content-between">
                <div class="col-lg-6 col-md-6 d-flex align-items-center">
                    <div>
                        <h2 class="site-title text-uppercase">Find the perfect name</h2>
                        <p>Order your favourite domain now from <span>&euro;1.99</span> /year</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <form action="https://freakhosting.com/clientarea/cart.php?a=add&domain=register" method="post">
                        <div class="input-group mb-3">
                            <input type="text" name="query" size="20" class="form-control" placeholder="eg. example.com" >
                            <button class="btn" type="submit"><i class="fas fa-search"></i> Search</button>
                        </div>
                    </form>
                    <ul>
                    <li>.com</li>
                    <li>.ro</li>
                    <li>.net</li>
                    <li>.org</li>
                    <li>.info</li>
                    <li>.biz</li>
                    <li>.online</li>
                    <li>.shop</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="domains py-5">
        <div class="container-fluid container-freak">
            <h2 class="site-title text-uppercase mb-5">List of Available Extensions</h2>
            <div class="row">
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.com</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 10.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.ro</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 8.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.net</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 14.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.org</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 13.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.info</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 4.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.biz</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 6.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.co.uk</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 8.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.uk</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 8.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.online</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 2.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.shop</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 33.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.store</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 2.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.site</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 1.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.website</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 2.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.live</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 3.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.vip</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 16.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.xyz</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 2.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.eu</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 1.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.me</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 4.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.gg</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 62.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.co</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 12.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://freakhosting.com/clientarea/cart.php?a=add&domain=register">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h2 class="mb-4">.to</h2>
                                <h4>Starting from</h4>
                                <span class="w-100 d-block">&euro; 61.99 / year</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    
    <div class="faq py-5">
        <div class="container-fluid container-freak">
            <h2 class="site-title text-uppercase mb-5">Frequently Asked Questions</h2>
            <div class="accordion" id="accordionExample">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    How do I pay?
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>Available payment methods by which you can purchase a service are: Paypal, Credit Card, Paysafecard, Cryptocurrencies, Bank Transfer</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingTwo">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                                How long does it take to activate a purchased domain?
                                </button>
                            </h2>
                            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>The registration of a domain with any extension displayed on the site will be activated immediately after making the payment.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingThree">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                                What do I do if I did not receive the data of the purchased service by email?
                                </button>
                            </h2>
                            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>In case you did not receive the data by email, please also check the SPAM section, sometimes it may be there. If the email is nowhere to be found, please open a ticket at the Billing department.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingFour">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                                What is a domain?
                                </button>
                            </h2>
                            <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>Each website has a specific name to identify it on the web, called a domain. The domain name must be unique and lead to only one website. That's why you have to check if the domain name you want is still free and not already taken.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingFive">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
                                How do I check the availability of a domain?
                                </button>
                            </h2>
                            <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>You can check the availability of a domain name using the search function displayed on this page. Simply enter your ideal name and you will be presented with a list of relevant options to purchase.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingSix">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="true" aria-controls="collapseSix">
                                What is domain extension?
                                </button>
                            </h2>
                            <div id="collapseSix" class="accordion-collapse collapse" aria-labelledby="headingSix" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>An extension is the end of a domain name. Extensions are commonly referred to as TLD (Top-Level Domain), suffix or domain root.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php require 'includes/footer.php'; ?>


 


<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="589395cd-679f-45bb-a565-c01d847f512b";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

<script src="https://cdn.websitepolicies.io/lib/cconsent/cconsent.min.js" defer></script><script>window.addEventListener("load",function(){window.wpcb.init({"border":"thin","corners":"small","colors":{"popup":{"background":"#222222","text":"#ffffff","border":"#2ED2FA"},"button":{"background":"#2ED2FA","text":"#000000"}},"padding":"small","margin":"small","fontsize":"small","content":{"href":"https://freakhosting.com/legal"}})});</script>

</body>
</html>