<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-DXGFWYGN7R"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-DXGFWYGN7R');
    </script>

    <!-- Meta tags -->
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
    <link rel="shorticon" type="image/x-icon" href="assets/images/favicon.ico">
    <!-- Page title -->
    <title>Teamspeak3 TS3 Server Hosting | FREAKHOSTING</title>
    <meta name="description" content="Premium Teamspeak3 (TS3) Server Hosting, Path.net DDoS Protection, Instant Activation, Support 24/7. Host your own cheap & reliable TS3 Server now!">
    <meta name="keywords" content="teamspeak3 hosting,teamspeak3 server hosting,ts3 hosting,ts3 server hosting,ts3 host,ts3 server host,premium teampeak3 hosting,free teampeak3 hosting,best teampeak3 hosting,affordable teampeak3 hosting,cheap teampeak3 hosting,linux teampeak3 hosting,rent teampeak3 server,24/7 support,ddos protection,europe,usa,game hosting,freakhosting">
    <meta name="robots" content="index,follow">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="blue">
    <meta name="format-detection" content="telephone=yes">
    <meta name="theme-color" content="#2ed2fa">

    <link rel="alternate" hreflang="x-default" href="https://freakhosting.com/teamspeak3-server-hosting" />
	<link rel="alternate" hreflang="en" href="https://freakhosting.com/teamspeak3-server-hosting" />
	<link rel="alternate" hreflang="ro" href="https://freakhosting.com/ro/gazduire-host-teamspeak3" />

    <link rel="canonical" href="https://freakhosting.com/teamspeak3-server-hosting" />

	<meta property="og:locale" content="en_US">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Teamspeak3 TS3 Server Hosting | FREAKHOSTING">
    <meta property="og:description" content="Premium Teamspeak3 (TS3) Server Hosting, Path.net DDoS Protection, Instant Activation, Support 24/7. Host your own cheap & reliable TS3 Server now!">
    <meta property="og:url" content="https://freakhosting.com/teamspeak3-server-hosting">
    <meta property="og:site_name" content="freakhosting.com">
    <meta property="og:image" content="https://freakhosting.com/assets/marketing/banneren.png">
  
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@freakhosting">
    <meta name="twitter:creator" content="@freakhosting">
    <meta name="twitter:description" content="Premium Teamspeak3 (TS3) Server Hosting, Path.net DDoS Protection, Instant Activation, Support 24/7. Host your own cheap & reliable TS3 Server now!">
    <meta name="twitter:title" content="Teamspeak3 TS3 Server Hosting | FREAKHOSTING">
    <meta name="twitter:image" content="https://freakhosting.com/assets/marketing/banneren.png">


    <!-- FontAwesome 5 Pro -->
    <link href="https://cdn.jsdelivr.net/gh/hung1001/font-awesome-pro@0ac23ca/css/all.css" rel="stylesheet" type="text/css">

    <!-- Raleway Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

	<!-- Bootstrap 5.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="assets/css/custom.css">

 

    <!-- Alternative Google Analytics -->
    <script defer data-domain="freakhosting.com" src="https://plausible.io/js/script.js"></script>
  

<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Product",
  "name": "Teamspeak3 TS3 Server Hosting | FREAKHOSTING",
  "image": "https://freakhosting.com/assets/marketing/banneren.png",
  "description": "Premium Teamspeak3 (TS3) Server Hosting, Path.net DDoS Protection, Instant Activation, Support 24/7. Host your own cheap & reliable TS3 Server now!",
  "url": "https://freakhosting.com/teamspeak3-server-hosting",
  "brand": {
    "@type": "Brand",
    "name": "FREAKHOSTING",
    "logo": "https://freakhosting.com/assets/images/logo.png"
  },
  "offers": {
    "@type": "Offer",
    "itemCondition": "https://schema.org/NewCondition",
    "availability": "https://schema.org/InStock",
    "price": "4.99",
    "priceCurrency": "EUR"
  },
  "hasMerchantReturnPolicy": {
    "@type": "MerchantReturnPolicy",
    "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
    "merchantReturnDays": 3
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.7",
    "bestRating": "5",
    "ratingCount": "73"
  },
  "review": {
    "@type": "Review",
    "author": {
      "@type": "Person",
      "name": "TrustPilot"
    }
  }
}
</script>

</head>
<body>

	<?php require 'includes/header.php'; ?>
    <div class="header-inner" style="background-image: url('assets/images/services-header/teamspeak3.webp');background-size: cover;height: 400px;">
        <div class="container-fluid container-freak h-100">
            <div class="row d-flex justify-content-between align-items-center h-100">
                <div class="col-lg-8">
                    <h2> <span>TS3</span> Hosting</h2>
                    <p>Elevate your gaming experience with FREAKHOSTING, your premium choice for hosting Teamspeak3 (TS3) servers. With strategic locations in Europe or the USA, our dedicated hosting service ensures optimal gameplay. Benefit from advanced DDoS protection provided by Path.net, capable of supporting an impressive 12TBps. We offer enterprise infrastructure, powered by the latest generation Intel I9 or AMD Ryzen 9 processors, for swift, secure, and low-latency connections. Trust FREAKHOSTING to host your gaming world, and step into the future of immersive gaming.</p>
                </div>
            </div>
        </div>
    </div>

<!-- Game Packages -->
<div class="game-packages pt-5 pb-1">
		<div class="container-fluid container-freak">
			<h2 class="site-title text-uppercase mb-5">Latest Offers</h2>
			<div class="row">
				<div class="col-md-3">
	                <div class="card mb-4">
	                	<div class="overlay">
	                    	<img class="card-img-top" src="assets/images/teamspeak3.webp" alt="TS3 Hosting Icon">
	                    </div>
	                    <div class="card-header text-center"><img src="assets/images/game-icons/teamspeak3.webp" alt="Teamspeak3 Hosting"> Teamspeak3</div>
	                    <div class="card-body">
	                        <h5 class="card-title text-center"><span>&euro; 9.99</span><span class="slot">/mo</span></h5>
	                        <ul class="text-left">
                            <li><i class="fas fa-microchip"></i> AMD Ryzen 9 5900x</li>
								<li><i class="fas fa-users"></i> Slots 64</li>
								<li><i class="fas fa-rss"></i> Port 9987</li>
								<li><i class="fas fa-file-certificate"></i> ATHP License</li>
								<li><i class="fas fa-key"></i> Yatqa Access</li>
								<li><i class="fas fa-code"></i> Advanced DDoS Protection</li>
                                <li><i class="fas fa-hourglass-half"></i> Uptime 99.5%</li>
								<li><i class="fas fa-headset"></i> Support 24/7</li>

	                        </ul>
	                        <a data-bs-toggle="modal" data-bs-target="#plan-one" class="btn w-100">
                                <i class="fas fa-globe"></i> Choose Location
                            </a>
	                    </div>
	                </div>
            	</div>
            	<div class="col-md-3">
	                <div class="card mb-4">
	                	<div class="overlay">
	                    	<img class="card-img-top" src="assets/images/teamspeak3.webp" alt="TS3 Hosting Icon">
	                    </div>
	                    <div class="card-header text-center"><img src="assets/images/game-icons/teamspeak3.webp" alt="Teamspeak3 Hosting"> Teamspeak3</div>
	                    <div class="card-body">
	                        <h5 class="card-title text-center"><span>&euro; 19.99</span><span class="slot">/mo</span></h5>
	                        <ul class="text-left">
                            <li><i class="fas fa-microchip"></i> AMD Ryzen 9 5900x</li>
								<li><i class="fas fa-users"></i> Slots 128</li>
								<li><i class="fas fa-rss"></i> Port 9987</li>
								<li><i class="fas fa-file-certificate"></i> ATHP License</li>
								<li><i class="fas fa-key"></i> Yatqa Access</li>
								<li><i class="fas fa-code"></i> Advanced DDoS Protection</li>
                                <li><i class="fas fa-hourglass-half"></i> Uptime 99.5%</li>
								<li><i class="fas fa-headset"></i> Support 24/7</li>

	                        </ul>
	                        <a data-bs-toggle="modal" data-bs-target="#plan-one" class="btn w-100">
                                <i class="fas fa-globe"></i> Choose Location
                            </a>
	                    </div>
	                </div>
            	</div>
            	<div class="col-md-3">
	                <div class="card mb-4">
	                	<div class="overlay">
	                    	<img class="card-img-top" src="assets/images/teamspeak3.webp" alt="TS3 Hosting Icon">
	                    </div>
	                    <div class="card-header text-center"><img src="assets/images/game-icons/teamspeak3.webp" alt="Teamspeak3 Hosting"> Teamspeak3</div>
	                    <div class="card-body">
	                        <h5 class="card-title text-center"><span>&euro; 39.99</span><span class="slot">/mo</span></h5>
	                        <ul class="text-left">
                            <li><i class="fas fa-microchip"></i> AMD Ryzen 9 5900x</li>
								<li><i class="fas fa-users"></i> Slots 256</li>
								<li><i class="fas fa-rss"></i> Port 9987</li>
								<li><i class="fas fa-file-certificate"></i> ATHP License</li>
								<li><i class="fas fa-key"></i> Yatqa Access</li>
								<li><i class="fas fa-code"></i> Advanced DDoS Protection</li>
                                <li><i class="fas fa-hourglass-half"></i> Uptime 99.5%</li>
								<li><i class="fas fa-headset"></i> Support 24/7</li>

	                        </ul>
	                        <a data-bs-toggle="modal" data-bs-target="#plan-one" class="btn w-100">
                                <i class="fas fa-globe"></i> Choose Location
                            </a>
	                    </div>
	                </div>
            	</div>
            	<div class="col-md-3">
	                <div class="card mb-4">
	                	<div class="overlay">
	                    	<img class="card-img-top" src="assets/images/teamspeak3.webp" alt="TS3 Hosting Icon">
	                    </div>
	                    <div class="card-header text-center"><img src="assets/images/game-icons/teamspeak3.webp" alt="Teamspeak3 Hosting"> Teamspeak3</div>
	                    <div class="card-body">
	                        <h5 class="card-title text-center"><span>&euro; 79.99</span><span class="slot">/mo</span></h5>
	                        <ul class="text-left">
                            <li><i class="fas fa-microchip"></i> AMD Ryzen 9 5900x</li>
								<li><i class="fas fa-users"></i> Slots 512</li>
								<li><i class="fas fa-rss"></i> Port 9987</li>
								<li><i class="fas fa-file-certificate"></i> ATHP License</li>
								<li><i class="fas fa-key"></i> Yatqa Access</li>
								<li><i class="fas fa-code"></i> Advanced DDoS Protection</li>
                                <li><i class="fas fa-hourglass-half"></i> Uptime 99.5%</li>
								<li><i class="fas fa-headset"></i> Support 24/7</li>

	                        </ul>
	                        <a data-bs-toggle="modal" data-bs-target="#plan-one" class="btn w-100">
                                <i class="fas fa-globe"></i> Choose Location
                            </a>
	                    </div>
	                </div>
            	</div>
			</div>
		</div>
	</div>

	<div class="server-features pt-5 pb-1">
		<div class="container-fluid container-freak">
			<h2 class="site-title text-uppercase mb-5">What we offer ?</h2>
			<div class="row">
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/24-hours.svg" alt="Support 24/7">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Support <span class="d-block">24/7</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">We are always here for you. Our 24/7 Support Team is here to solve any commercial or technical problem that you might have.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/shield.svg" alt="DDoS Protection">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">DDoS <span class="d-block">Protection</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">All services are on enterprise level of protection against DDoS attacks up to 12TBps to keep your services online with ease.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/uptime.svg" alt="99.99% Uptime">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Uptime <span class="d-block">99.5%</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">Thanks to our infrastructure located in the best datacenters with the most reliable uplinks, we offer our clients an uptime of 99.5% for their services.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/cpu.svg" alt="Processor">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Ultra-Fast <span class="d-block">Infrastructure</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">Our hosting network is built on high-performance Intel I9 dedicated servers resulting in unmatched game server performance.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/panel.svg" alt="Control Panel">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Game <span class="d-block">Panel</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">WISP is the premium control panel we use for game servers, a user-friendly and efficient panel perfect for you to manage any project.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/active.svg" alt="Manual Setup">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Manual <span class="d-block">Setup</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">After the placement of an order, the installation process of our server is manual and can take up to 6 hours after payment confirmation.</p>
							<br>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


    <div class="preview-panel py-5">
        <div class="container">
            <h2 class="site-title text-uppercase text-center">Powered by WISP</h2>
            <p class="text-center mb-5">WISP is the premium panel used by us to control gaming services, offering our clients a user-friendly and efficient platform for project management.</p>
            <ul class="nav nav-justified" data-bs-tabs="" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-bs-toggle="tab" href="#manage" role="tab">
                        <img class="img-fluid mb-1" src="assets/images/gpanel.svg" alt="Server Administration">
                        <h4>Server Administration</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="tab" href="#config" role="tab">
                        <img class="img-fluid mb-1" src="assets/images/plus.svg" alt="File Manager">
                        <h4>File Manager</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="tab" href="#fastdll" role="tab">
                        <img class="img-fluid mb-1" src="assets/images/dll.svg" alt="FastDL">
                        <h4>Auto FastDLL</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="tab" href="#console" role="tab">
                        <img class="img-fluid mb-1" src="assets/images/console.svg" alt="Console">
                        <h4>Remote Console</h4>
                    </a>
                </li>
            </ul>
            <div class="tab-content mt-5">
                <div class="tab-pane active text-center" id="manage" role="tabpanel">
                    <img class="img-fluid rounded" src="assets/images/gpanel.webp" alt="Manage your Server">
                </div>
                <div class="tab-pane text-center" id="config" role="tabpanel">
                    <img class="img-fluid rounded" src="assets/images/plus.webp" alt="File Manager">
                </div>
                <div class="tab-pane text-center" id="fastdll" role="tabpanel">
                    <img class="img-fluid rounded" src="assets/images/dll.webp" alt="Auto FastDLL">
                </div>
                <div class="tab-pane text-center" id="console" role="tabpanel">
                    <img class="img-fluid rounded" src="assets/images/console.webp" alt="Remote Console">
                </div>
            </div>
        </div>
    </div>

    <div class="dark py-5">
        <div class="container-fluid container-freak">
            <h2 class="site-title text-uppercase mb-5">Info Game</h2>
            <p>Teamspeak3 is a widely used voice-over-IP (VoIP) solution designed to provide high-quality voice communication for gamers, businesses, and various other user groups. Known for its crystal-clear audio and robust security features, Teamspeak3 facilitates real-time voice chat, file transfers, and text messaging among users within a chat channel. Its customizability and scalability make it a popular choice for anyone needing reliable voice communication, whether it's for coordinating a raid in a gaming environment or conducting a virtual team meeting.<br><br>
            When it comes to hosting your Teamspeak3 server, FREAKHOSTING is the definitive choice. We offer top-tier server quality backed by an infrastructure designed for low-latency and fault-tolerant communication. In a platform where audio clarity and uptime are critical, FREAKHOSTING excels by providing an environment that makes your voice interactions seamless and efficient. Plus, with our 24/7 customer support, you're never alone when you encounter issues or have questions; we're always here to ensure your Teamspeak3 server performs at its best. So, why settle for less when you can have the best? Make the smart choice for your voice communication needs—choose FREAKHOSTING.</p>
        </div>
    </div>

    <div class="faq py-5">
        <div class="container-fluid container-freak">
            <h2 class="site-title text-uppercase mb-5">Frequently Asked Questions</h2>
            <div class="accordion" id="accordionExample">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
									How do I pay?
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
									<p>Available payment methods by which you can purchase a service are: Paypal, Credit Card, Paysafecard, Bitcoin, SMS, Bank Transfer.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingTwo">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
									How long does it take to activate a purchased service?
                                </button>
                            </h2>
                            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>After the placement of an order, the installation process of our server is manual and can take up to 6 hours after payment confirmation.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingThree">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
									What do I do if I did not receive the data of the purchased service by email?
                                </button>
                            </h2>
                            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
									<p>In case you did not receive the data by email, please also check the SPAM section, sometimes it may be there. If the email is nowhere to be found, please open a ticket at the Billing department.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingFour">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                                	What infrastructure is FREAKHOSTING using for game servers?
                                </button>
                            </h2>
                            <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>All game servers purchased from us are hosted on high-performance Intel I9 or AMD Ryzen 9 servers with ultra-fast NVMe SSD storage and DDR4 RAM.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingFive">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
                                Where are the game servers hosted? What latency will I get on the server?
                                </button>
                            </h2>
                            <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>Our hosting network is located in Romania, USA and ddos protection,europe,germany,romania,usa,dallas in the best datacenters with the most reliable uplinks. Depending on which location you will choose we will try to provide the lowest latency possible.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php require 'includes/footer.php'; ?>

    <!-- Modals for Plans -->
    <!-- Modal -->
    <div class="modal fade" id="plan-one" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="far fa-times"></i></button>
                    <h2 class="text-center mt-5">Pick the location of your server</h2>
                    <p class="text-center mb-5">Choose the location closest to users, for the best connection speeds!</p>
                    <div class="row">
                        <div class="col-lg-4 mx-auto">
                            <a href="https://freakhosting.com/clientarea/store/voice-hosting/teamspeak3-hosting" class="mo">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-center country">
                                            <div class="d-flex align-items-center">
                                                <img src="assets/images/romania.svg" alt="Romania">
                                            </div>
                                            <div class="d-flex align-items-center ms-3">
                                                <div>
                                                    <h4 class="mb-0">Romania</h4>
                                                    <p class="mb-0">Bacau</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-4 mx-auto">
                            <a href="https://freakhosting.com/clientarea/store/voice-hosting/teamspeak3-hosting" class="mo">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-center country">
                                            <div class="d-flex align-items-center">
                                                <img src="assets/images/ddos protection,europe,germany,romania,usa,dallas.svg" alt="ddos protection,europe,germany,romania,usa,dallas">
                                            </div>
                                            <div class="d-flex align-items-center ms-3">
                                                <div>
                                                    <h4 class="mb-0">ddos protection,europe,germany,romania,usa,dallas</h4>
                                                    <p class="mb-0">Frankfurt</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-4 mx-auto">
                            <a href="https://freakhosting.com/clientarea/store/voice-hosting/teamspeak3-hosting" class="mo">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-center country">
                                            <div class="d-flex align-items-center">
                                                <img src="assets/images/usa.svg" alt="USA">
                                            </div>
                                            <div class="d-flex align-items-center ms-3">
                                                <div>
                                                    <h4 class="mb-0">USA</h4>
                                                    <p class="mb-0">Dallas</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 


<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="589395cd-679f-45bb-a565-c01d847f512b";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

<script src="https://cdn.websitepolicies.io/lib/cconsent/cconsent.min.js" defer></script><script>window.addEventListener("load",function(){window.wpcb.init({"border":"thin","corners":"small","colors":{"popup":{"background":"#222222","text":"#ffffff","border":"#2ED2FA"},"button":{"background":"#2ED2FA","text":"#000000"}},"padding":"small","margin":"small","fontsize":"small","content":{"href":"https://freakhosting.com/legal"}})});</script>

</body>
</html>