<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-DXGFWYGN7R"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-DXGFWYGN7R');
    </script>

    <!-- Meta tags -->
	  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="width">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
    <!-- Page title -->
    <title>AMD Ryzen Gaming VPS - FreakHosting</title>
    <meta name="description" content="Premium Gaming Virtual Private Server (VPS) KVM Hosting perfect for FiveM, Minecraft, CS2, Rust, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable gaming VPS server now!">
    <meta name="keywords" content="virtual private server,vps,gaming,kvm,lxc,windows,linux,intel,amd,ryzen,I9,Ryzen 9,gaming,dedicated,server,root,hosting,host,server,servers,ddos,protection,ddos protection,path.net,linux,windows,gaming,game,romania,bacau,germany,frankfurt,usa,dallas,texas,vps,dedicated server,premium,best,affordable,cheap,how to,freakhosting">
    <meta name="robots" content="index,follow">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="blue">
    <meta name="apple-mobile-web-app-title" content="FREAKHOSTING GameServer" />
    <link rel="apple-touch-icon" href="/assets/images/touch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/images/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="167x167" href="/assets/images/touch-icon-ipad-retina.png">


    <meta name="format-detection" content="telephone=yes">
    <meta name="theme-color" content="#2ed2fa">


	<link rel="alternate" hreflang="x-default" href="https://freakhosting.com/vps" />
     
    <link rel="alternate" hreflang="en-GB" href="https://freakhosting.com/vps" />
    <link rel="canonical" href="https://freakhosting.com/vps" />

	  <meta property="og:locale" content="en_US">
    <meta property="og:type" content="website">
    <meta property="og:title" content="AMD Ryzen Gaming VPS - FreakHosting">
    <meta property="og:description" content="Premium Gaming Virtual Private Server (VPS) KVM Hosting perfect for FiveM, Minecraft, CS2, Rust, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable gaming VPS server now!">
    <meta property="og:url" content="https://freakhosting.com/vps">
    <meta property="og:site_name" content="freakhosting.com">
    <meta property="og:image" content="https://freakhosting.com/assets/marketing/vps.jpg">
  
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@freakhosting">
    <meta name="twitter:creator" content="@freakhosting">
    <meta name="twitter:description" content="Premium Gaming Virtual Private Server (VPS) KVM Hosting perfect for FiveM, Minecraft, CS2, Rust, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable gaming VPS server now!">
    <meta name="twitter:title" content="AMD Ryzen Gaming VPS - FreakHosting">
    <meta name="twitter:image" content="https://freakhosting.com/assets/marketing/vps.jpg">

    <!-- FontAwesome 5 Pro -->
    <link href="https://cdn.jsdelivr.net/gh/hung1001/font-awesome-pro@0ac23ca/css/all.css" rel="stylesheet" type="text/css">

    <!-- Raleway Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
	  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

	  <!-- Bootstrap 5.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="assets/css/slider.css">
    <link rel="stylesheet" type="text/css" href="assets/css/custom.css">

 


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Product",
    "@id": "https://freakhosting.com/vps",
    "url": "https://freakhosting.com/vps",
    "name": "AMD Ryzen Gaming VPS - FreakHosting",
    "image": "https://freakhosting.com/assets/marketing/banneren.png",
    "description": "Premium Gaming Virtual Private Server (VPS) KVM Hosting perfect for FiveM, Minecraft, CS2, Rust, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable gaming VPS server now!",
    "brand": {
      "@type": "Organization",
      "name": "FREAKHOSTING",
      "url": "https://freakhosting.com",
      "logo": "/assets/images/logo.webp"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "4.9",
      "ratingCount": "107",
      "bestRating": "5",
      "worstRating": "1"
    },
    "review": [{
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Alexandru"
      },
      "reviewBody": "Bought a GTA5 server hosting and I am more than happy with the service provided. Setup the server with TxAdmin in couple minutes and had no issues. Hope it will stay like this"
    }, {
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Spritz"
      },
      "reviewBody": "Absolutely amazing, there may be some features that arent included, but for the price it is way more than excellent. The support team in their discord responds quick and always seems to help out, aswell as solve problems. I will continue to use this hosting service for my FiveM server as it stays the best for pricing and my needs. Thank you FreakHosting for providing such an amazing experience and service."
    }, {
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Alex"
      },
      "reviewBody": "Best service, never let me down, best quality and extremely fast customer service!"
    }],
    "offers": {
      "@type": "AggregateOffer",
      "lowPrice": 4.99,
      "highPrice": 63.99,
      "priceCurrency": "EUR",
      "offerCount": 4,
      "offers": [{
        "@type": "Offer",
        "price": 4.99,
        "name": "KVM-1",
        "description": "GAMING KVM VPS HOSTING",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best GAMING KVM VPS HOSTING on the market"
        },
        "url": "https://freakhosting.com/vps",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 7.99,
        "name": "KVM-2",
        "description": "GAMING KVM VPS HOSTING",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best GAMING KVM VPS HOSTING on the market"
        },
        "url": "https://freakhosting.com/vps",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 11.99,
        "name": "KVM-3",
        "description": "GAMING KVM VPS HOSTING",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best GAMING KVM VPS HOSTING on the market"
        },
        "url": "https://freakhosting.com/vps",
        "priceValidUntil": "2024-12-31",
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "sameDayDelivery": true, // Indicate that the delivery is instant or on the same day
          "shippingTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": "0" // Set to 0 days if instant
          }
        }
      }, {
        "@type": "Offer",
        "price": 11.99,
        "name": "KVM-4",
        "description": "GAMING KVM VPS HOSTING",
        "priceCurrency": "EUR",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "FREAKHOSTING",
          "url": "https://freakhosting.com",
          "logo": "/assets/images/logo.webp",
          "slogan": "Get the best GAMING KVM VPS HOSTING on the market"
        },
        "url": "https://freakhosting.com/vps"
      }]
    }
  }
</script>

</head>
<body>

	<?php require 'includes/header.php'; ?>
    <div class="header-inner" style="background-image: url('assets/images/services-header/vps-header.webp');background-size: cover;height: 400px;">
        <div class="container-fluid container-freak h-100">
            <div class="row d-flex justify-content-between align-items-center h-100">
                <div class="col-lg-8">
                    <h1>KVM Gaming VPS  </h2>
                    <p>Premium Gaming Virtual Private Server (VPS) KVM Hosting perfect for FiveM, Minecraft, CS2, Rust, Path.net 17Tbps Best DDoS Protection, Instant Activation, Support 24/7. Available in Romania, Germany, USA Dallas. Rent your own cheap & reliable gaming VPS server now!</p>
                </div>
            </div>
        </div>
    </div>

    <div class="game-plans py-5">
        <div class="container-fluid container-freak">
            <h2 class="site-title text-uppercase mb-5">Gaming KVM VPS - Path.net</h2>
            <div class="vps-plans">
                
                <table>
                    <thead class="d-none">
                        <tr>
                            <th>Name</th>
                            <th>Memory</th>
                            <th>Disk Space</th>
                            <th>Bandwidth</th>
                            <th>Delivery</th>
                            <th>Location</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                      <tr>
                            <td data-label="Name">
                                <h2>1 <span>vCPU</span></h2>
                                <span class="sub">AMD Ryzen 9 5950X</span>
                            </td>
                            <td data-label="Memory">
                                <h2>2GB</h2>
                                <span class="sub">DDR4 RAM</span>
                            </td>
                            <td data-label="Storage">
                                <h2>50GB</h2>
                                <span class="sub">NVMe</span>
                            </td>
                            <td data-label="Bandwidth">
                                <h2> 1/10 Gbps</h2>
                                <span class="sub">Network</span>
                            </td>
                            <td data-label="Delivery">
                                <h2> 120 seconds</h2>
                                <span class="sub">Delivery Time</span>
                            </td>
                            <td data-label="Location">
                                <h2> Germany</h2>
                                <span class="sub">Location</span>
                            </td>
                            <td data-label="Price">
                                <div class="card">
                                    <div class="row d-flex justify-content-between">
                                        <div class="col-lg-6 d-flex align-items-center">
                                            <span class="price"> &euro;4.99 <span>/mo</span></span>
                                        </div>
                                        <div class="col-lg-6">
                                            <a href="/clientarea/store/vps/vps-1-1" class="btn btn-primary">BUY</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td data-label="Name">
                                <h2>2 <span>vCPU</span></h2>
                                <span class="sub">AMD Ryzen 9 5950X</span>
                            </td>
                            <td data-label="Memory">
                                <h2>4GB</h2>
                                <span class="sub">DDR4 RAM</span>
                            </td>
                            <td data-label="Storage">
                                <h2>100GB</h2>
                                <span class="sub">NVMe</span>
                            </td>
                            <td data-label="Bandwidth">
                                <h2> 1/10 Gbps</h2>
                                <span class="sub">Network</span>
                            </td>
                            <td data-label="Delivery">
                                <h2> 120 seconds</h2>
                                <span class="sub">Delivery Time</span>
                            </td>
                            <td data-label="Location">
                                <h2> Germany</h2>
                                <span class="sub">Location</span>
                            </td>
                            <td data-label="Price">
                                <div class="card">
                                    <div class="row d-flex justify-content-between">
                                        <div class="col-lg-6 d-flex align-items-center">
                                            <span class="price"> &euro;7.99 <span>/mo</span></span>
                                        </div>
                                        <div class="col-lg-6">
                                            <a href="/clientarea/store/vps/vps-2-1" class="btn btn-primary">BUY</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td data-label="Name">
                                <h2>2 <span>vCPU</span></h2>
                                <span class="sub">AMD Ryzen 9 5950X</span>
                            </td>
                            <td data-label="Memory">
                                <h2>6GB</h2>
                                <span class="sub">DDR4 RAM</span>
                            </td>
                            <td data-label="Storage">
                                <h2>150GB</h2>
                                <span class="sub">NVMe</span>
                            </td>
                            <td data-label="Bandwidth">
                                <h2> 1/10 Gbps</h2>
                                <span class="sub">Network</span>
                            </td>
                            <td data-label="Delivery">
                                <h2> 120 seconds</h2>
                                <span class="sub">Delivery Time</span>
                            </td>
                            <td data-label="Location">
                                <h2> Germany</h2>
                                <span class="sub">Location</span>
                            </td>
                            <td data-label="Price">
                                <div class="card">
                                    <div class="row d-flex justify-content-between">
                                        <div class="col-lg-6 d-flex align-items-center">
                                            <span class="price"> &euro;11.99 <span>/mo</span></span>
                                        </div>
                                        <div class="col-lg-6">
                                            <a href="/clientarea/store/vps/vps-3-1" class="btn btn-primary">BUY</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td data-label="Name">
                                <h2>3 <span>vCPU</span></h2>
                                <span class="sub">AMD Ryzen 9 5950X</span>
                            </td>
                            <td data-label="Memory">
                                <h2>8GB</h2>
                                <span class="sub">DDR4 RAM</span>
                            </td>
                            <td data-label="Storage">
                                <h2>200GB</h2>
                                <span class="sub">NVMe</span>
                            </td>
                            <td data-label="Bandwidth">
                                <h2> 1/10 Gbps</h2>
                                <span class="sub">Network</span>
                            </td>
                            <td data-label="Delivery">
                                <h2> 120 seconds</h2>
                                <span class="sub">Delivery Time</span>
                            </td>
                            <td data-label="Location">
                                <h2> Germany</h2>
                                <span class="sub">Location</span>
                            </td>
                            <td data-label="Price">
                                <div class="card">
                                    <div class="row d-flex justify-content-between">
                                        <div class="col-lg-6 d-flex align-items-center">
                                            <span class="price"> &euro;15.99 <span>/mo</span></span>
                                        </div>
                                        <div class="col-lg-6">
                                            <a href="/clientarea/store/vps/vps-4-1" class="btn btn-primary">BUY</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td data-label="Name">
                                <h2>4 <span>vCPU</span></h2>
                                <span class="sub">AMD Ryzen 9 5950X</span>
                            </td>
                            <td data-label="Memory">
                                <h2>12GB</h2>
                                <span class="sub">DDR4 RAM</span>
                            </td>
                            <td data-label="Storage">
                                <h2>250GB</h2>
                                <span class="sub">NVMe</span>
                            </td>
                            <td data-label="Bandwidth">
                                <h2> 1/10 Gbps</h2>
                                <span class="sub">Network</span>
                            </td>
                            <td data-label="Delivery">
                                <h2> 120 seconds</h2>
                                <span class="sub">Delivery Time</span>
                            </td>
                            <td data-label="Location">
                                <h2> Germany</h2>
                                <span class="sub">Location</span>
                            </td>
                            <td data-label="Price">
                                <div class="card">
                                    <div class="row d-flex justify-content-between">
                                        <div class="col-lg-6 d-flex align-items-center">
                                            <span class="price"> &euro;23.99 <span>/mo</span></span>
                                        </div>
                                        <div class="col-lg-6">
                                            <a href="/clientarea/store/vps/vps-5-1" class="btn btn-primary">BUY</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td data-label="Name">
                                <h2>5 <span>vCPU</span></h2>
                                <span class="sub">AMD Ryzen 9 5950X</span>
                            </td>
                            <td data-label="Memory">
                                <h2>16GB</h2>
                                <span class="sub">DDR4 RAM</span>
                            </td>
                            <td data-label="Storage">
                                <h2>300GB</h2>
                                <span class="sub">NVMe</span>
                            </td>
                            <td data-label="Bandwidth">
                                <h2> 1/10 Gbps</h2>
                                <span class="sub">Network</span>
                            </td>
                            <td data-label="Delivery">
                                <h2> 120 seconds</h2>
                                <span class="sub">Delivery Time</span>
                            </td>
                            <td data-label="Location">
                                <h2> Germany</h2>
                                <span class="sub">Location</span>
                            </td>
                            <td data-label="Price">
                                <div class="card">
                                    <div class="row d-flex justify-content-between">
                                        <div class="col-lg-6 d-flex align-items-center">
                                            <span class="price"> &euro;31.99 <span>/mo</span></span>
                                        </div>
                                        <div class="col-lg-6">
                                            <a href="/clientarea/store/vps/vps-6" class="btn btn-primary">BUY</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td data-label="Name">
                                <h2>6 <span>vCPU</span></h2>
                                <span class="sub">AMD Ryzen 9 5950X</span>
                            </td>
                            <td data-label="Memory">
                                <h2>24GB</h2>
                                <span class="sub">DDR4 RAM</span>
                            </td>
                            <td data-label="Storage">
                                <h2>400GB</h2>
                                <span class="sub">NVMe</span>
                            </td>
                            <td data-label="Bandwidth">
                                <h2> 1/10 Gbps</h2>
                                <span class="sub">Network</span>
                            </td>
                            <td data-label="Delivery">
                                <h2> 120 seconds</h2>
                                <span class="sub">Delivery Time</span>
                            </td>
                            <td data-label="Location">
                                <h2> Germany</h2>
                                <span class="sub">Location</span>
                            </td>
                            <td data-label="Price">
                                <div class="card">
                                    <div class="row d-flex justify-content-between">
                                        <div class="col-lg-6 d-flex align-items-center">
                                            <span class="price"> &euro;47.99 <span>/mo</span></span>
                                        </div>
                                        <div class="col-lg-6">
                                            <a href="/clientarea/store/vps/vps-7" class="btn btn-primary">BUY</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td data-label="Name">
                                <h2>7 <span>vCPU</span></h2>
                                <span class="sub">AMD Ryzen 9 5950X</span>
                            </td>
                            <td data-label="Memory">
                                <h2>32GB</h2>
                                <span class="sub">DDR4 RAM</span>
                            </td>
                            <td data-label="Storage">
                                <h2>500GB</h2>
                                <span class="sub">NVMe</span>
                            </td>
                            <td data-label="Bandwidth">
                                <h2> 1/10 Gbps</h2>
                                <span class="sub">Network</span>
                            </td>
                            <td data-label="Delivery">
                                <h2> 120 seconds</h2>
                                <span class="sub">Delivery Time</span>
                            </td>
                            <td data-label="Location">
                                <h2> Germany</h2>
                                <span class="sub">Location</span>
                            </td>
                            <td data-label="Price">
                                <div class="card">
                                    <div class="row d-flex justify-content-between">
                                        <div class="col-lg-6 d-flex align-items-center">
                                            <span class="price"> &euro;63.99 <span>/mo</span></span>
                                        </div>
                                        <div class="col-lg-6">
                                            <a href="/clientarea/store/vps/vps-8" class="btn btn-primary">BUY</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>

                

                <h2 class="site-title text-uppercase my-5">Operating Systems</h2>
                <div class="row oper-syst">
                    <div class="col-md-3 text-center">
                        <img src="assets/images/centos.svg" class="img-fluid" alt="centos logo">
                        <h3>Centos</h3>
                    </div>
                        <div class="col-md-3 text-center">
                            <img src="assets/images/debian.svg" class="img-fluid" alt="debian logo">
                            <h3>Debian</h3>
                        </div>
                        <div class="col-md-3 text-center">
                            <img src="assets/images/ubuntu.svg" class="img-fluid" alt="ubuntu logo">
                            <h3>Ubuntu</h3>
                        </div>
                        <div class="col-md-3 text-center">
                            <img src="assets/images/windows.svg" class="img-fluid" alt="windows logo">
                            <h3>Windows</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


	<div class="server-features pt-5 pb-1">
		<div class="container-fluid container-freak">
			<h2 class="site-title text-uppercase mb-5">What we offer ?</h2>
			<div class="row">
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/24-hours.svg" alt="Support 24/7">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Support <span class="d-block">24/7</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">We are always here for you. Our 24/7 Support Team is here to solve any commercial or technical problem that you might have.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/shield.svg" alt="DDoS Protection">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">DDoS <span class="d-block">Protection</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">All services are on enterprise level of protection against DDoS attacks up to 17Tbps to keep your services online with ease.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/uptime.svg" alt="99.99% Uptime">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Uptime <span class="d-block">99.5%</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">Thanks to our infrastructure located in the best datacenters with the most reliable uplinks, we offer our clients an uptime of 99.5% for their services.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/cpu.svg" alt="Processor">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Ultra-Fast <span class="d-block">Infrastructure</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">Our hosting network is built on high-performance AMD Ryzen 9 dedicated servers resulting in unmatched game server performance.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/panel.svg" alt="Control Panel">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Operating <span class="d-block">System</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">Windows, Ubuntu, Debian, Centos and many others. You have a variety of operating systems to choose from with availability for the latest version.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="card mb-4">
						<div class="card-body">
							<div class="d-flex align-items-center mb-4">
								<div class="d-flex align-items-center">
									<img src="assets/images/active.svg" alt="Instant Setup">
								</div>
								<div class="d-flex justify-content-between">
									<div class="d-flex align-items-center">
										<h5 class="mb-0 ms-3">Instant <span class="d-block">Setup</span></h5>
									</div>
								</div>
							</div>
							<p class="mb-0">After the placement of an order, the installation process of our services begins immediately after payment confirmation.</p>
							<br>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


    <div class="faq py-5">
        <div class="container-fluid container-freak">
            <h2 class="site-title text-uppercase mb-5">Frequently Asked Questions</h2>
            <div class="accordion" id="accordionExample">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
									How do I pay?
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
									<p>Available payment methods by which you can purchase a service are: Paypal, Credit Card, Paysafecard, Cryptocurrencies, Bank Transfer</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingTwo">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
									How long does it take to activate a purchased service?
                                </button>
                            </h2>
                            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>After the placement of an order, the installation process of our server begins immediately after payment confirmation.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingThree">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
									What do I do if I did not receive the data of the purchased service by email?
                                </button>
                            </h2>
                            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
									<p>In case you did not receive the data by email, please also check the SPAM section, sometimes it may be there. If the email is nowhere to be found, please open a ticket at the Billing department.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingFour">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                                	What infrastructure is FREAKHOSTING using for game servers?
                                </button>
                            </h2>
                            <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>All game servers purchased from us are hosted on high-performance AMD Ryzen 9 servers with ultra-fast NVMe SSD storage and DDR4 RAM memory.</p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingFive">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
                                Where are the game servers hosted? What latency will I get on the server?
                                </button>
                            </h2>
                            <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>Our VPS hosting network is located in Germany in the best datacenter with the most reliable uplinks. Depending on which location you will choose we will try to provide the lowest latency possible.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php require 'includes/footer.php'; ?>
    <script>
    const PRIVATE_RADE_SETTINGS = {
      ON_VALUE_2: {
        // key for 2gb ram
        price: 4.99, // price in XX currency
        cpu: 1,   
        ram: 2, // ram in gb
        capacity: 25, // hdd or ssd capacity in gb
        order_btn_link: "https://freakhosting.com/clientarea/store/vps/vps-1-1", // link for order
      },
      ON_VALUE_4: {
        // key for 4gb ram
        price: 7.99, // price in XX currency
        cpu: 2,
        ram: 4, // ram in gb
        capacity: 50, // hdd or ssd capacity in gb
        order_btn_link: "https://freakhosting.com/clientarea/store/vps/vps-2-1", // link for order
      },
      ON_VALUE_6: {
        // key for 4gb ram
        price: 11.99, // price in XX currency
        cpu: 3,
        ram: 6, // ram in gb
        capacity: 75, // hdd or ssd capacity in gb
        order_btn_link: "https://freakhosting.com/clientarea/store/vps/vps-3-1", // link for order
      },
      ON_VALUE_8: {
        // key for 8gb ram
        price: 15.99, // price in XX currency
        cpu: 4,
        ram: 8, // ram in gb
        capacity: 100, // hdd or ssd capacity in gb
        order_btn_link: "https://freakhosting.com/clientarea/store/vps/vps-4-1", // link for order
      },
      ON_VALUE_12: {
        // key for 8gb ram
        price: 23.99, // price in XX currency
        cpu: 5,
        ram: 12, // ram in gb
        capacity: 150, // hdd or ssd capacity in gb
        order_btn_link: "https://freakhosting.com/clientarea/store/vps/vps-5-1", // link for order
      },
      ON_VALUE_16: {
        // key for 12gb ram
        price: 31.99, // price in XX currency
        cpu: 6,
        ram: 16, // ram in gb
        capacity: 200, // hdd or ssd capacity in gb
        order_btn_link: "https://freakhosting.com/clientarea/store/vps/vps-6", // link for order
      },
      ON_VALUE_24: {
        // key for 12gb ram
        price: 47.99, // price in XX currency
        cpu: 7,
        ram: 24, // ram in gb
        capacity: 250, // hdd or ssd capacity in gb
        order_btn_link: "https://freakhosting.com/clientarea/store/vps/vps-7", // link for order
      },
      ON_VALUE_32: {
        // key for 12gb ram
        price: 63.99, // price in XX currency
        cpu: 8,
        ram: 32, // ram in gb
        capacity: 300, // hdd or ssd capacity in gb
        order_btn_link: "https://freakhosting.com/clientarea/store/vps/vps-8", // link for order
      },
    };

    const updateSliderHTML = (value) => {
      const price = document.getElementById("rade_price");
      const cpu = document.getElementById("rade_cpu");
      const ram = document.getElementById("rade_ram");
      const capacity = document.getElementById("rade_capacity");
      const orderLink = document.getElementById("rade_order_link");
      let item = PRIVATE_RADE_SETTINGS["ON_VALUE_2"];

      switch (value) {
        case "2":
          item = PRIVATE_RADE_SETTINGS["ON_VALUE_2"];
          price.textContent = item.price;
          cpu.textContent = item.cpu;
          ram.textContent = item.ram;
          capacity.textContent = item.capacity;
          orderLink.setAttribute("href", item.order_btn_link);
          break;
        case "4":
          item = PRIVATE_RADE_SETTINGS["ON_VALUE_4"];
          price.textContent = item.price;
          cpu.textContent = item.cpu;
          ram.textContent = item.ram;
          capacity.textContent = item.capacity;
          orderLink.setAttribute("href", item.order_btn_link);
          break;
        case "6":
          item = PRIVATE_RADE_SETTINGS["ON_VALUE_6"];
          price.textContent = item.price;
          cpu.textContent = item.cpu;
          ram.textContent = item.ram;
          capacity.textContent = item.capacity;
          orderLink.setAttribute("href", item.order_btn_link);
          break;
        case "8":
          item = PRIVATE_RADE_SETTINGS["ON_VALUE_8"];
          price.textContent = item.price;
          cpu.textContent = item.cpu;
          ram.textContent = item.ram;
          capacity.textContent = item.capacity;
          orderLink.setAttribute("href", item.order_btn_link);
          break;
        case "12":
          item = PRIVATE_RADE_SETTINGS["ON_VALUE_12"];
          price.textContent = item.price;
          cpu.textContent = item.cpu;
          ram.textContent = item.ram;
          capacity.textContent = item.capacity;
          orderLink.setAttribute("href", item.order_btn_link);
          break;
        case "16":
          item = PRIVATE_RADE_SETTINGS["ON_VALUE_16"];
          price.textContent = item.price;
          cpu.textContent = item.cpu;
          ram.textContent = item.ram;
          capacity.textContent = item.capacity;
          orderLink.setAttribute("href", item.order_btn_link);
          break;
        case "24":
          item = PRIVATE_RADE_SETTINGS["ON_VALUE_24"];
          price.textContent = item.price;
          cpu.textContent = item.cpu;
          ram.textContent = item.ram;
          capacity.textContent = item.capacity;
          orderLink.setAttribute("href", item.order_btn_link);
          break;
        case "32":
          item = PRIVATE_RADE_SETTINGS["ON_VALUE_32"];
          price.textContent = item.price;
          cpu.textContent = item.cpu;
          ram.textContent = item.ram;
          capacity.textContent = item.capacity;
          orderLink.setAttribute("href", item.order_btn_link);
          break;
      }
    };

    (function () {
      "use strict";

      var init = function () {
        updateSliderHTML(8);
        var slider2 = new rSlider({
          target: "#slider",
          values: [2, 4, 6, 8, 12, 16, 24, 32],
          range: false,
          set: [4],
          tooltip: true,
          onChange: function (vals) {
            updateSliderHTML(vals);
          },
        });
      };
      window.onload = init;
    })();
    </script>

 


<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="589395cd-679f-45bb-a565-c01d847f512b";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

<script src="https://cdn.websitepolicies.io/lib/cconsent/cconsent.min.js" defer></script><script>window.addEventListener("load",function(){window.wpcb.init({"border":"thin","corners":"small","colors":{"popup":{"background":"#222222","text":"#ffffff","border":"#2ED2FA"},"button":{"background":"#2ED2FA","text":"#000000"}},"padding":"small","margin":"small","fontsize":"small","content":{"href":"https://freakhosting.com/legal"}})});</script>

</body>
</html>